# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18e32b2826173ce02b01586f308ef742bb9e7ae27d40ae423f175ed66dcb1233442f94cd513caedf1508009f72a8128e84b961d6bd0168dcf8abb432c83355d3

test:
  secret_key_base: f7d7b93799c32f0258c7f06085278b49b68e812c34b456999175433586287e3635328ffa6550d96c8ec94a7b0199a87b65907262d0bcf5c130727551e56ed223

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
